In [1]:
import numpy as np
from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize

class ComplexProblem(ElementwiseProblem):
    def __init__(self):
        super().__init__(n_var=3, n_obj=2, n_constr=2, xl=np.array([-5, -5, -5]), xu=np.array([5, 5, 5]))

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[0]**2 + x[1]**2 + x[2]**2
        f2 = (x[0]-1)**2 + x[1]**2 + (x[2]-1)**2

        g1 = x[0] + x[1] - 1
        g2 = 1 - x[0] + x[1]

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]

algorithm = NSGA2(pop_size=100)
problem = ComplexProblem()

res = minimize(problem,
               algorithm,
               ('n_gen', 100),
               verbose=True)

print(f"Best solution found:\nX = {res.X}\nF = {res.F}\nG = {res.G}")


n_gen  |  n_eval  | n_nds  |     cv_min    |     cv_avg    |      eps      |   indicator  
     1 |      100 |      1 |  0.000000E+00 |  3.1555678571 |             - |             -
     2 |      200 |      1 |  0.000000E+00 |  0.1092351093 |  0.000000E+00 |             f
     3 |      300 |      1 |  0.000000E+00 |  0.000000E+00 |  0.000000E+00 |             f
     4 |      400 |      1 |  0.000000E+00 |  0.000000E+00 |  0.8707643957 |         ideal
     5 |      500 |      2 |  0.000000E+00 |  0.000000E+00 |  1.8806682078 |         ideal
     6 |      600 |      4 |  0.000000E+00 |  0.000000E+00 |  0.1693985712 |         ideal
     7 |      700 |      5 |  0.000000E+00 |  0.000000E+00 |  0.2011978005 |         ideal
     8 |      800 |      9 |  0.000000E+00 |  0.000000E+00 |  0.0644619808 |         ideal
     9 |      900 |      9 |  0.000000E+00 |  0.000000E+00 |  0.0295897073 |         ideal
    10 |     1000 |      8 |  0.000000E+00 |  0.000000E+00 |  0.0633637760 |             f

    95 |     9500 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0001097666 |             f
    96 |     9600 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0002620282 |             f
    97 |     9700 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0004415393 |             f
    98 |     9800 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0008161748 |             f
    99 |     9900 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0010426312 |             f
   100 |    10000 |    100 |  0.000000E+00 |  0.000000E+00 |  0.0011774298 |             f
Best solution found:
X = [[ 0.55878631 -0.44201835  0.03053754]
 [ 1.00686744 -0.01020314  0.98626835]
 [ 0.9888867  -0.03222446  0.93880748]
 [ 1.00359338 -0.03222446  0.98626835]
 [ 0.87984094 -0.12310012  0.87452795]
 [ 0.86613375 -0.1388124   0.80860775]
 [ 0.87984094 -0.12486743  0.76427711]
 [ 0.55878631 -0.44201835  0.06972264]
 [ 0.57204582 -0.42998453  0.15330972]
 [ 0.93915571 -0.06897927  0.84510741]
 [ 0.56946697 -0.43252623  0.0917286 ]
